### PR TITLE
Basic documentation stubs

### PR DESCRIPTION
**Pull request by eddowh**
Covers #3 

Theme: `sphinx_rtd_theme` (readthedocs)

Preview:

okq-docs-preview

### CODE REVIEW

**Comment by eddowh** [comment]
Ready to be examined.

**Comment by hrbonz** [comment]
merged in 58a457b7e52a93a18dfe5da2ca4fd30e15d4ee99

**Comment by eddowh** [comment]
Wait, why was this closed?

**Comment by hrbonz** [comment]
because it was merged...

**Pull request closed without merging**
