### PR TITLE
flake8 in tox

### PR DESCRIPTION
**Pull request by eddowh**
Basic configuration for flake8 testing in `tox.ini`.

### CODE REVIEW

**Comment by hrbonz** [comment]
Where's my new `dex-requirements.txt` with flake8? :)

Don't forget to change `dev-requirements.in` then compile it with `pip-tools`, the steps could probably be added to `README.rst` at the same time.

``rst
Compile requirement file
------------------------

.. code:: shell

    $ pip install pip-tools
    $ pip-compile requirements.in
```

**Comment by eddowh** [comment]
What you're referring to is `requirements-dev.in`.

But what about the original `dev_requirements.txt` file just hanging there? Do I delete it?

**Comment by eddowh** [comment]
Also, what is the difference between `requirements.in` and `requirements-dev.in`? How did you create them?

**Comment by eddowh** [comment]
Meanwhile, I haven't touched the `requirements.in` and just added `flake8==2.5.4` manually into `requirements-dev.in`. I'm pretty sure that is not the way to do it so... any help is appreciated here.

**Comment by hrbonz** [comment]
Oh yeah correct, `git rm` the `dev_...` file but move the package references in `requirements-dev.in`.

The requirements is used for production, the derquirements-dev is used for dev environment. As you can see requirements-dev first line is referencing requirements so dev will have production packages plus a few.

**Comment by eddowh** [comment]
```bash
$ cat dev_requirements.txt
-r requirements.txt
tox
wheel
```

Do we not pin these packages to a specific version or do you just want me to append `tox` and `wheel` onto the new `requirements-dev.in`?

**Comment by hrbonz** [comment]
Please pin in the process, I didn't do it before and that's a mistake.

**Comment by hrbonz** [comment]
Again here, changes are so small that you can just squash the two commits together. New commit could be:
```
add flake8 testing to tox

Deleted old dev requirements and moved the packages to new dev requirements file.
```

**Pull request merged**
